### ISSUE TITLE
9: Reservation look up page:

### ISSUE THREAD

**Issue by redbaron131** [joelmichaelavery/Moffat-Bay#13]
Note: Provide customers with a page to look up previous reservation. The page should include a field to search by reservation ID or email address and display a summary of the reservation. List the room size, number of guests, and check-in/check-out dates.

**Comment by iRegretn0thing** [comment]
Provided a look up page. Room size, number of guests, and check-in/check-out dates can be provided in a separate page such as the "booking a reservation page" or "your active reservation."

**Comment by redbaron131** [comment]
The page should include a field to search by **reservation ID** or **email address** and display a summary of the reservation.
Do not add anything more than the requirements.
