### ISSUE TITLE
5: Registration page:

### ISSUE THREAD

**Issue by redbaron131** [joelmichaelavery/Moffat-Bay#9]
Students can pick the number of fields, but at minimum, there should be fields for email address, first name, last name, telephone, and password. Additional comments: All customers should be assigned a unique customer-Id. All customers should use their email address as the “username” field and the password should be at least 8 characters in length and include one uppercase and one lowercase letter (hint: use regular expression). Passwords should be hashed and/or encrypted using standard security practices (use the Internet for ideas/code snippets; be sure to cite all external authors).

**Comment by redbaron131** [comment]
There should be fields for email address, first name, last name, telephone, and password.
Password  will have requirements of at least 8 characters in length and include one uppercase and one lowercase letter

**Comment by redbaron131** [comment]
How is this going?

**Comment by joelmichaelavery** [comment]
Haven’t had a bunch of time yet, is it due next week?
